Add a unittest
Blagues-API/blagues-api-py pull request #1
Opened 2021-06-10 16:38 UTC by coco875

2021-06-12 20:34 UTC, DraftProducts reviewed
Je vais faire les corrections 👍

2021-06-12 20:34 UTC, DraftProducts commented on test.py
> +TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzI0OTQxNDcyMzY3NjQwNTk2IiwibGltaXQiOjEwMCwia2V5IjoiOHJ2QVdPaEhzdHJlNFRPMFA0MXNZRlMzZTVuajA3QnJOOER2eUwyVFhvczRWUGZ0a0UiLCJjcmVhdGVkX2F0I
Evite de mettre en clair ton token comme ça

PS: Je te conseilles de le regénérer

2021-06-12 20:34 UTC, DraftProducts commented on test.py
> +        reponce = loop.run_until_complete(blagues.random())
Ce n'est pas la peine d'utiliser asyncio, c'est build-in, suffit de mettre async devant la fonction

2021-06-12 20:34 UTC, DraftProducts commented on test.py
> +        reponce = loop.run_until_complete(blagues.random(disallow=["dark"]))
Ici aussi

2021-06-12 20:34 UTC, DraftProducts commented on test.py
> +        reponce = loop.run_until_complete(blagues.random_categorized(disallow=["dark"]))
Ici aussi

2021-06-12 20:34 UTC, DraftProducts commented on test.py
> +        reponce = loop.run_until_complete(blagues.from_id(1))
Et là aussi

2021-06-12 20:34 UTC, DraftProducts commented on test.py
> +        reponce = loop.run_until_complete(blagues.random())
Réponse s'écrit avec un s
généralement on l'ecrit en anglais ce mot clé donc `response` 👍

2021-06-12 21:14 UTC, coco875 commented on test.py
> +TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzI0OTQxNDcyMzY3NjQwNTk2IiwibGltaXQiOjEwMCwia2V5IjoiOHJ2QVdPaEhzdHJlNFRPMFA0MXNZRlMzZTVuajA3QnJOOER2eUwyVFhvczRWUGZ0a0UiLCJjcmVhdGVkX2F0I
oublié c'était pour faciliter les test

2021-06-12 23:15 UTC, DraftProducts approved these changes

2021-06-13 12:56 UTC, merged

2021-06-13 13:00 UTC, baptiste0928 requested changes

2021-06-13 13:00 UTC, baptiste0928 commented on blagues_api/main.py
> +    def __str__(self):
Pour respecter les règles de style du [PEP8](https://www.python.org/dev/peps/pep-0008/#blank-lines), il faudrait laisser une ligne vide avant et après la méthode.

> Method definitions inside a class are surrounded by a single blank line.

2021-06-13 13:03 UTC, baptiste0928 commented
Afin de rendre les tests plus clairs, on pourrait envisager l'utilisation de [pytest](https://docs.pytest.org/en/6.2.x/), qui permet d'utiliser directement le keyword `assert` au lieu de méthodes, et propose un écosystème de plugins, notamment [pytest-asyncio](https://pypi.org/project/pytest-asyncio/) qui permet de simplifier les tests asynchrones.

2021-06-13 13:07 UTC, baptiste0928 commented on test.py
> +    unittest.main()
Attention, `unittest` n'est pas importé, seulement `TestCase`.

2021-06-13 13:08 UTC, baptiste0928 commented on test.py
> +import os
Cet import est inutilisé.

2021-06-13 13:11 UTC, DraftProducts commented
> Afin de rendre les tests plus clairs, on pourrait envisager l'utilisation de [pytest](https://docs.pytest.org/en/6.2.x/), qui permet d'utiliser directement le keyword `assert` au lieu de méthodes, et propose un écosystème de plugins, notamment [pytest-asyncio](https://pypi.org/project/pytest-asyncio/) qui permet de simplifier les tests asynchrones.

Yes je suis d'accord