Chore/update dependencies
Blagues-API/blagues-api-py pull request #6
Opened 2022-07-10 21:11 UTC by Swiizyy

Mise à niveau des dépendances avec test passé avec succès : 
 - aiohttp ✅
 - pydantic ✅
 - pytest ✅
 - pytest-asyncio ✅
 - python-dotenv ✅
 - poetry-core ✅

2022-07-10 23:48 UTC, DraftProducts reviewed
Aucun breaking change ?

2022-07-10 23:51 UTC, Swiizyy commented
Nan j'ai été le premier surpris 😦 

J'ai fait tout les tests et il sont tous passé nickel 👌

2022-07-11 00:10 UTC, DraftProducts approved these changes

2022-07-11 08:53 UTC, baptiste0928 reviewed
Il n'y a aucun intérêt à modifier ces versions, hormis contraindre inutilement les utilisateurs de la bibliothèque à utiliser une version plus récente là où ce n'est pas nécessaire. Ces versions plus récentes sont déjà supportées puisqu'il ne s'agit que de versions mineures.

Les seules dépendances utiles à mettre à jour sont les dev dependencies, comme il s'agit de mises à jour majeures dans les trois cas, et que ça n'affecte pas les utilisateurs de la bibliothèque.

2022-07-11 08:55 UTC, baptiste0928 requested changes
Voir le commentaire précédent.

2022-07-11 10:03 UTC, Swiizyy commented
@baptiste0928 étant donné qu'il va falloir déployer une nouvelle version pour l'ajouts de l'Endpoint count je pense que sa serais bien de le faire en même temps tu trouve pas ?
Et je pense que c'est toujours mieux d'avoir les dernière versions des paquets ... Tu en pense quoi ?

2022-07-11 11:37 UTC, baptiste0928 commented
> Et je pense que c'est toujours mieux d'avoir les dernière versions des paquets 

Les contraintes de dépendances actuelles permettent déjà d'avoir les dernières versions, puisqu'il n'y a aucune mise à jour majeure dans ces dépendances (c.f. [semver](https://semver.org/)), et que les [caret requirements (`^`)](https://python-poetry.org/docs/dependency-specification/#caret-requirements) de Poetry permettent d'utiliser n'importe laquelle des versions compatibles.

Donc par exemple, lorsque tu as `pydantic = "^1.8"`, c'est équivalent à  `pydantic = ">= 1.8, < 2.0"`, donc la version `1.9.1` peut être utilisée.  Hors, si tu mets `pydantic = "^1.9.1"`, tu empêches d'utiliser une version plus ancienne, alors qu'elle fonctionnerait aussi bien.

Si on n'a pas besoin de mettre à jour les contraintes de dépendances pour une vraie raison, à savoir si on utilise une fonctionnalité disponible uniquement à partir d'une certaine version, on ne doit pas modifier les contraintes. C'est à ceux qui utilisent la bibliothèque de mettre à jour leurs dépendances (et ils le pourront puisque les contraintes actuelles acceptent ces nouvelles versions). Cela permet par exemple à quelqu'un qui souhaite rester sur une ancienne version, pour une raison quelconque, de le faire.

2022-07-11 11:45 UTC, Swiizyy commented
D'accord merci pour l'info du coup on ne met a jour juste les dev dépendance ? 
Donc pytest , pytest-asyncio et python-dotenv c'est bien sa ?

2022-07-11 11:50 UTC, baptiste0928 commented
C'est ça :+1:  Pour les 3 dépendances de dev, il s'agit de mises à jour majeures, donc les nouvelles versions ne sont pas supportées par les contraintes actuelles (et on peut se permettre de mettre des contraintes plus fortes puisqu'elles ne sont utilisées que par nous).

2022-07-11 11:55 UTC, Swiizyy commented
C'est bon en tout cas merci pour les infos j'utile pas vraiment python donc je savais pas 😅

2022-07-11 11:56 UTC, baptiste0928 approved these changes

2022-07-11 12:00 UTC, merged

2022-07-11 12:03 UTC, baptiste0928 commented
C'est assez standard, la plupart des gestionnaires de dépendances suivent le semver. C'est exactement la même chose en javascript avec npm par exemple.

En Python, c'est un peu plus compliqué, car le gestionnaire de dépendances (`pip`) ne supporte pas réellement de manière standard de définir les dépendances. C'est pour ça qu'on utilise ici [Poetry](https://python-poetry.org/) qui permet d'avoir quelque chose de semblable à `npm`.